import { expect, test } from '@playwright/test'

test('приветствие: крупный бренд и кнопка Играть', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.boot-loader')).toHaveCount(0, { timeout: 8000 })
  await expect(page.locator('.screen--welcome')).toBeVisible()
  await expect(page.locator('.welcome__title')).toHaveAttribute('alt', 'Планета Мяу')
  await expect(page.getByRole('button', { name: 'Играть' })).toBeVisible()
  await expect(page.locator('.welcome__dock')).toBeVisible()
  await expect(page.locator('.welcome__hint')).toHaveCount(0)
  await expect(page.locator('.chrome')).toBeHidden()
  const welcomeSound = page.getByRole('button', { name: /Звук/ })
  await expect(welcomeSound).toHaveAttribute('aria-label', 'Звук включён')
  await welcomeSound.click()
  await expect(welcomeSound).toHaveAttribute('aria-label', 'Звук выключен')
  await welcomeSound.click()
  await expect(welcomeSound).toHaveAttribute('aria-label', 'Звук включён')
  await page.getByRole('button', { name: 'Играть' }).click()
  await expect(page.locator('.screen--menu')).toBeVisible({ timeout: 8000 })
  const menuSound = page.locator('.menu-sound')
  await expect(menuSound).toHaveAttribute('aria-label', 'Звук включён')
  await menuSound.click()
  await expect(menuSound).toHaveAttribute('aria-label', 'Звук выключен')
  await page.getByRole('button', { name: 'Назад' }).click()
  await expect(page.locator('.screen--welcome')).toBeVisible()
})
